### ISSUE TITLE
Installation on MacOSX hangs forever

### ISSUE THREAD

**Issue by BoltzmannEntropy** [QTechTheory/QuESTlink#166]
Hello,
I tried this on two different MAC notebooks with the same result: 
<img width="778" alt="Screenshot 2022-09-24 at 10 49 17" src="https://user-images.githubusercontent.com/91342039/192086933-b9759e02-dcbe-48f1-824e-5b0957eced42.png">
Nothing happens even after an hour, I do have an internet connection and I did try:
`CreateDownloadedQuESTEnv[] 
`
But the end results is the same. 

Thanks.

**Comment by TysonRayJones** [comment]
Hi there,
This likely means we're not choosing the correct pre-compiled binary, possibly because you are using a new ARM-based M1. We added support for ARM MacOS in the [latest release](https://github.com/QTechTheory/QuESTlink/releases/tag/v0.12), so if you now run...

```Mathematica
CreateDownloadedQuESTEnv[]
```
you should get QuESTlink running fine (else hopefully obtain a more informative error message!)
